# Generated by Django 2.2 on 2019-06-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('body_part1', models.CharField(max_length=100)),
                ('num_exercises1', models.PositiveSmallIntegerField()),
                ('body_part2', models.CharField(blank=True, max_length=100)),
                ('num_exercises2', models.PositiveSmallIntegerField(blank=True)),
                ('cardio', models.CharField(blank=True, max_length=100)),
                ('cardio_load', models.CharField(blank=True, max_length=100)),
                ('summary', models.CharField(max_length=100)),
            ],
        ),
    ]
