# Generated by Django 2.2 on 2019-06-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0003_auto_20190606_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='summary',
            field=models.TextField(),
        ),
    ]
