# Generated by Django 2.2 on 2019-06-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0005_workout_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='body_part2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='cardio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='cardio_load',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='num_exercises2',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
