# Generated by Django 2.2 on 2019-06-12 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0007_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
