# Generated by Django 2.2 on 2019-06-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0010_auto_20190612_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
